name: iptv_smatvpro_project
description: IPTV project similar to SmartersTV Pro
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.15.0
  provider: ^6.0.0
  video_player: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
